---
phases:
  artifacts:
    discard-paths: true
    files:
      - target/sl-project5-CICD.jar
  build:
    commands:
      - "echo -----------------------"
      - "echo -----------------------"
      - "echo Build started on `date`"
      - "echo -----------------------"
      - "echo -----------------------"
      - "mvn clean package"
      - "echo -----------------------"
  post_build:
    commands:
      - "echo -----------------------"
      - "echo -----------------------"
      - "echo Build completed on `date`"
      - "echo -----------------------"
      - "echo -----------------------"
version: 0.2


